name: Build schedule.json hourly

on:
  schedule:
    - cron: "0 * * * *"   # every hour
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Xvfb (virtual display)
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Install deps
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Scrape shows -> public/schedule.json (headed via Xvfb)
        env:
          DEBUG: pw:browser*,pw:api   # show detailed Playwright logs
        run: |
          set -e
          node -v
          xvfb-run -a npm run scrape || (
            echo 'Scrape failed; writing placeholder'
            mkdir -p public
            echo "[]" > public/schedule.json
          )

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
